from clay.graph import Edge, Graph, Node

graph = Graph(
    nodes=[
        Node("input"),
        Node("analyze"),
        Node("content"),
        Node("metadata"),
        Node("online"),
        Node("LLM knowledge"),
        Node("HyDE"),
        Node("search terms"),
        Node("generate"),
        Node("criteria"),
        Node("index"),
        Node("lookup"),
        Node("candidates"),
        Node("rerank"),
        Node("reranked"),
        Node("filter"),
        Node("tabular"),
        Node("final"),
    ],
    edges=[
        Edge("input", "analyze"),
        Edge("analyze", "content"),
        Edge("analyze", "metadata"),
        Edge("content", "HyDE"),
        Edge("online", "HyDE", flow=False),
        Edge("LLM knowledge", "HyDE", flow=False),
        Edge("HyDE", "search terms"),
        Edge("content", "generate"),
        Edge("generate", "criteria"),
        Edge("search terms", "lookup"),
        Edge("index", "lookup"),
        Edge("tabular", "lookup"),
        Edge("metadata", "lookup"),
        Edge("lookup", "candidates"),
        Edge("candidates", "rerank"),
        Edge("rerank", "reranked"),
        Edge("reranked", "filter"),
        Edge("criteria", "filter"),
        Edge("filter", "final"),
    ]
)
